### ISSUE TITLE
Change date format in creation of a lesson to DD/MM/YYYY instead of the us version.

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schulcloud-client#182]
[Trello](https://trello.com/c/j3EXGQGz/443-change-date-format-in-creation-of-a-lesson-to-dd-mm-yyyy-instead-of-the-us-version)

**Comment by niccokunzmann** [comment]
I think, if we implement a German/English translation, the date time format could be translated, too.

**Comment by shubhnik** [comment]
Hi, I would like to solve this bug. This would be my first contribution too :) . How can i reproduce this bug?

**Comment by shubhnik** [comment]
Hi @niccokunzmann ,sorry for late response, i was setting up the development environment and i got these eroors while testing the server https://gist.github.com/shubhnik/78a3507dd1cfbc90e253f0dacac65339

**Comment by shubhnik** [comment]
When i visit http://localhost:3100/ , the terminal outputs this error:
```
shubhnik@shubhnik-Satellite-C655:~/Desktop/Schul-Cloud/schulcloud-client$ npm run watch

> schulcloud-express@0.0.0 watch /home/shubhnik/Desktop/Schul-Cloud/schulcloud-client
> nodemon --watch ./ --watch views/ --watch controllers/ --watch build/ ./bin/www

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/shubhnik/Desktop/Schul-Cloud/schulcloud-client/**/* /home/shubhnik/Desktop/Schul-Cloud/schulcloud-client/views/**/* /home/shubhnik/Desktop/Schul-Cloud/schulcloud-client/controllers/**/* /home/shubhnik/Desktop/Schul-Cloud/schulcloud-client/build/**/*
[nodemon] starting `node ./bin/www`
Listening on port 3100
(node:17506) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: Error: connect ECONNREFUSED 127.0.0.1:3030
```

**Comment by pinussilvestrus** [comment]
@shubhnik This error often occurs when the schulcloud-server is not started completely. Does the server-output `Schul-Cloud application started on http://localhost:3030` on your Terminal? Sometimes it helps if you refresh your browser a couple of times.

**Comment by shubhnik** [comment]
I have logged in successfully :smile: ,I tried finding this issue,i found dates displayed as 07.05.2017 when i add tasks , so the need is to display it as 07/05/2017 or something else?AFAIK US dates have format MM/DD/YYYY , So can you please help me in finding the issue if its somewhere else ,Thanks :)

**Comment by pinussilvestrus** [comment]
@shubhnik which language is set in your browser? German or English? We found out last week that it depends on the browser-language which date-format is shown in the input's. We want it to always show the German date-format, but we are not sure whether this is possible with standard HTML-5 date-input's.

Maybe this ticket is obsolete, because German users will always have set German language in their browsers :)

**Comment by shubhnik** [comment]
so this issue no longer exists?

**Comment by pinussilvestrus** [comment]
No, I don't think so, except you find a way to set the date-format exactly. But I think there are more interesting issues to solve :)
