### ISSUE TITLE
Move area-label in feedback-form

### ISSUE THREAD

**Issue by pinussilvestrus** [schul-cloud/schulcloud-client#198]
Move the area-label in the feedback to the next line, with smaller font (e.g. "Bereich - Übersicht" in screenshot)

![image](https://cloud.githubusercontent.com/assets/9433996/25616631/46980386-2f3e-11e7-9eab-e0d80cffb6d4.png)

**Comment by pinussilvestrus** [comment]
[Trello](https://trello.com/c/IKC1NCcm/469-bitte-im-feedback-formualr-das-bereich-uberischt-in-eine-neue-zeile-und-kleiner-font-wunsch-von-meinel)

**Comment by DontLikeClouds** [comment]
Can I do this?

**Comment by DontLikeClouds** [comment]
@pinussilvestrus yo brother, can you pinpoint me to the problem?

**Comment by pinussilvestrus** [comment]
@DontLikeClouds hi bro, good to hear from you! Yeah, you can take it, if you like. You just have to move the `Bereich`-label to the next line, you found the code for this here: https://github.com/schul-cloud/schulcloud-client/blob/master/views/lib/forms/form-helpdesk.hbs
and here: https://github.com/schul-cloud/schulcloud-client/blob/master/static/scripts/loggedin.js

**Comment by pinussilvestrus** [comment]
@hkiefer will do it!
