### ISSUE TITLE
Verbindlichkeiten für Tests

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schulcloud-client#251]
Wir haben die Möglichkeit, Browsertests mit Browserstack zu schreiben.
Diese ermöglichen 
- Deutsche Textbeschreibungen von User-Stories.
- Dass Lehrer selbst diese Stories beitragen können
- Dass wir viele Stories automatisch gegen das live-system testen können

Ich sehe folgende Probleme:
1. Ich mache gerade den Antares-Client
2. Wenn ich als Bachelorprojektinterner was teste und es wird rot, wen interessiert das dann?

**Comment by pinussilvestrus** [comment]
zu 1. inwieweit ist das jetzt ein Problem?
zu 2. es interessiert insoweit, dass nur Travis Builds auf staging kommen, die grün sind. Rote werden nicht gemerged.

Welches Ziel hat dieses Ticket genau? Wir wissen, dass wir Browserstack haben und damit die Möglichkeit, UI-Tests zu schreiben. Es gibt auch ein [Trello-Ticket](https://trello.com/c/b2DxuNil/512-evaluate-user-testing-concept) dafür, nur hat David da denke ich momentan nicht wirklich Zeit. Wir haben momentan ebenfalls ca. 100 Trello-Tickets, die entweder im Backlog oder in Progress sind, ergo sind wir an vielen anderen Sachen dran (die Tickets für iOS und Android sind da nicht mal inbgeriffen).

**Comment by niccokunzmann** [comment]
Zu 2. Wenn ich einen neuen Test für ein Feature schreibe, dann ist der Test rot.
Wie sieht der Prozess aus, diesen Test in den master zu bekommen, samt Feature?

1. Test schreiben
2. Pull-request machen mit [NewFesture]
3. Issue öffnen, getaggt und auf PR verweisen
4. Jemand nimmt sich den Test und implementiert ihn.
5. Andere PR wird gemerged.

Würde das so für euch passen?

**Comment by MasterCarl** [comment]
Das klingt eigentlich ganz gut. Ich persönlich halte aber eigentlich sinnvoller, den Prozess so zu gliedern:
1. ein Issue/Trello-Ticket öffnen
2. Test schreiben
3. [PR mit WIP - Work in progress öffnen]
4. Feature implementieren
5. PR öffnen oder WIP-Tag entfernen
6. Code review
7. Merge

**Comment by pinussilvestrus** [comment]
Finde @MasterCarl ziemlich gut, erinnert sehr an die Struktur aus der SWT2-Vorlesung! :+1:

**Comment by niccokunzmann** [comment]
Danke! :)
