### ISSUE TITLE
Selbstständige Seiten einbinden

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schulcloud-client#301]
Wir möchten zwei Seiten machen, die 
- Server und Mongodb nicht brauchen
- Auch ohne Authetifizierung erreichbar sind
- Einfach zu editieren sein sollten (HTML)

Seiten:
- Such-Frontend
- Materialuploadverwaltung

Wie können diese eingepflegt werden?

Ideen:
- node module
- iframe
- copy&paste beim build

Wichtig:
- Design sollte gleich bleiben

Was denkt ihr?

@schul-cloud/bp (@kremer-io)

**Comment by MasterCarl** [comment]
Ich denke, es wird schwierig, eine Seite zu bauen, die ohne Server auskommt und trotzdem erreichbar ist. ;) Wieso soll es gerade pures HTML sein? Es wird halt schwierig, Header und Footer konsistent einzubinden, ohne auf die Templating-Engine zurückzugreifen. Allerdings kann man innerhalb von Handlebars-Templates problemlos HTML verwenden. Du kannst einfach eine bestehende Seite kopieren und die `content`-Sektion austauschen.
Das Einzige, was wir eventuell noch machen müssten, ist den Fall zu unterstützen, dass der User nicht eingeloggt ist und dementsprechend die Navigationsleiste versteckt werden sollte.

**Comment by ArneOb** [comment]
Ich habe die Ideen "iframe" "copy&paste beim build" nicht verstanden.
Ansonsten würde ich mich jetzt dem Thema nähern ...
Würde mal einen Vorschlag machen und Ihr dürft dann bullshit stempeln :-)

**Comment by pinussilvestrus** [comment]
Die genannten Seiten werden ja im https://github.com/schul-cloud/schulcloud-content-editor eingebaut. Deswegen kann das hier geschlossen werden.
