### ISSUE TITLE
npm install fails in schulcloud-client directory

### ISSUE THREAD

**Issue by vedk** [schul-cloud/schulcloud-client#346]
I was trying to setup Schul-Cloud on the following Ubuntu machine (output of `uname -a`):
`Linux ved-laptop 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Following instructions from [here](https://schul-cloud.github.io/blog/2017-04-21/setup-development-under-ubuntu). I ran `npm install` in the `schulcloud-client` directory, but it fails with the following error:
```
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file /home/ved/.npm/debug/2.6.8/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/ved/.npm/debug/2.6.8/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ved/Documents/schul-cloud/schulcloud-client/npm-debug.log
```
The verbose log is here: [npm-debug.log.txt](https://github.com/schul-cloud/schulcloud-client/files/1203231/npm-debug.log.txt)

**Comment by Langleu** [comment]
seems like the package.json had a problem.
I tried to reproduce your problem with a new ubuntu 16.04 VM and could not get that error.
Please try to either clone the repo again or do `git pull` to get the latest changes.

**Comment by vedk** [comment]
Thank you.

I shall certainly the suggestion and update on the same.

Thank you once again.

Am 06.08.2017 11:19 nachm. schrieb "Lars Lange" <notifications@github.com>:

seems like the package.json had a problem.
I tried to reproduce your problem with a new ubuntu 16.04 VM and could not
get that error.
Please try to either clone the repo again or do git pull to get the latest
changes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/schul-cloud/schulcloud-client/issues/346#issuecomment-320521674>,
or mute the thread

**Comment by pinussilvestrus** [comment]
Tell us when this can be closed 🙂  @vedk

**Comment by vedk** [comment]
Sorry @pinussilvestrus, but I will be able to try the solution given by @Langleu only on coming Sunday (13th August). This issue will be surely closed as soon as possible.

**Comment by vedk** [comment]
A `sudo npm cache clear` solved the problem. Thank you very much.
