### ISSUE TITLE
No "Bist du dir sicher?" modal when deleting things in admin area

### ISSUE THREAD

**Issue by pinussilvestrus** [schul-cloud/schulcloud-client#384]
In all views, we display a modal when deleting stuff, like when deleting files:

![image](https://user-images.githubusercontent.com/9433996/29862303-80042118-8d6c-11e7-8e0e-8efc8554163c.png)

This is not displayed on the tables in the administration page.

Hint: The deleting function is located here: [base.js](https://github.com/schul-cloud/schulcloud-client/blob/master/static/scripts/base.js#LL167)

[Trello-Ticket](https://trello.com/c/XPXwmpIu/544-beim-l%C3%B6schen-eines-kurses-kommt-keine-bist-du-sicher-frage)

**Comment by essal0815** [comment]
Who ever solved it ?! Someone did.
![screen shot 2018-01-04 at 16 58 30](https://user-images.githubusercontent.com/28301364/34572719-62a87c76-f172-11e7-9920-548132eb0d0b.png)
