### ISSUE TITLE
Sort functionality for files

### ISSUE THREAD

**Issue by pinussilvestrus** [schul-cloud/schulcloud-client#385]
The files in the file section should be sortable by
- Date
- Name
- FileType 
- whateveryouwant

[Trello-Ticket](https://trello.com/c/rVlHoIDI/575-sortierfunktion-datum-person-name)

**Comment by pinussilvestrus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sortierfunktion (Datum, Person, Name...)](https://trello.com/c/rVlHoIDI/575-sortierfunktion-datum-person-name)

**Comment by adrianjost** [comment]
Should be easy when this PR is ready: https://github.com/schul-cloud/schulcloud-client/pull/593
