### ISSUE TITLE
Discuss German url-paths

### ISSUE THREAD

**Issue by pinussilvestrus** [schul-cloud/schulcloud-client#398]
We've got a recommendation that we should use German urls in the client. So instead of using: `/courses/... ` it should routed as `/faecher/...` and so on. On my opinion, english urls are better. It is not common to use German paths, even if we are a German project with mainly German users. 

What do you think about it?

**Comment by niccokunzmann** [comment]
I agree. We can close the issue if there is no discussion after a week and whenever it turns up, we can reference this or re-opan.
