### ISSUE TITLE
Show "Add to Kurs" Button in content for DemoTeacher 

### ISSUE THREAD

**Issue by Charle42** [schul-cloud/schulcloud-client#448]
At the moment it is not obvious to the demo user how he can add materials to courses.

**Comment by pinussilvestrus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show "Add to Kurs" Button in content for DemoTeacher](https://trello.com/c/Lx1ZE9bq/779-show-add-to-kurs-button-in-content-for-demoteacher)
