### ISSUE TITLE
Docker: Handle Gulp

### ISSUE THREAD

**Issue by kremer-io** [schul-cloud/schulcloud-client#459]
Check:
- Implement gulp watch in extra container / task
- Avoid gulp watch initial run on each start
- Avoid restart loop with nodemon

**Comment by kremer-io** [comment]
- Implement gulp watch in extra container / task
> fixed
- Avoid restart loop with nodemon
> fixed

still open:
- Avoid gulp watch initial run on each start

**Comment by kremer-io** [comment]
@pascalhpi Hier hattest du mal was probiert, oder?

**Comment by pascalhpi** [comment]
ja da bin ich dran, ich denke übermorgen hab ich da was vorzeigbares ;)

**Comment by pascalhpi** [comment]
@kremer-io hast du mal probiert wie/ob das neue gulpfile mit docker funktioniert?

**Comment by pinussilvestrus** [comment]
@kremer-io Ist das mittlerweile gefixed?
