### ISSUE TITLE
[content] less tags or collapsing tags

### ISSUE THREAD

**Issue by Langleu** [schul-cloud/schulcloud-client#481]
![image](https://user-images.githubusercontent.com/9141483/32601627-90f74cd4-c543-11e7-8c2b-81e0ead13050.png)

show around 5-13 tags, the rest is collapsed and can be shown if wanted or hovered over...

**Comment by jprberlin** [comment]
+1
show 10, with a more link that display all tags

**Comment by kremer-io** [comment]
Collapsing Tags will be made in a future version. For now stripping (just showing less tags) is ok.
