### ISSUE TITLE
cant create multiple new topics

### ISSUE THREAD

**Issue by pascalhpi** [schul-cloud/schulcloud-client#496]
newly created topics apparently get key = null -> only one topic with key = null is allowed.
steps to reproduce: login as teacher, create 2 new topics for any course -> internal server error. server log:
[Thu Nov 23 2017 14:41:28] [LOG]   error:   (409) Route: /lessons/ - E11000 duplicate key error index: schulcloud.lessons.$shareToken_1 dup key: { : null }
[Thu Nov 23 2017 14:41:28] [LOG]   info:      Conflict: E11000 duplicate key error index: schulcloud.lessons.$shareToken_1 d  up key: { : null }

**Comment by kremer-io** [comment]
Auf schul-cloud.org geht es noch

**Comment by kremer-io** [comment]
@Langleu @pinussilvestrus Kann sein, dass der shareToken indiziert ist und daher nur einmal null vergeben werden darf?

**Comment by Langleu** [comment]
klar sharetoken ist unique, frage ist eher was hast du gemacht, dass er neuerdings null ist?

**Comment by pinussilvestrus** [comment]
Der ist indiziert ja, aber der wird eig. auch Zufällig vergeben, wodurch da eig. gar kein duplicate error passieren sollte... muss ich mir mal angucken

**Comment by kremer-io** [comment]
Fehler muss ich im aktuellen Master wohl mit eingeschlichen haben

**Comment by pinussilvestrus** [comment]
Gab es bei topics denn überhaupt ne änderung?

**Comment by Langleu** [comment]
eigentlich ja noch nicht

**Comment by pinussilvestrus** [comment]
@pascalhpi konnte den Bug gerade nicht reproduzieren. Habe zwei neue Themen erstellt und es kam kein Fehler. Die haben auch beide keinen shareToken bekommen, der wird ja auch nicht auf null oder so gesetzt beim Erstellen ..

**Comment by jprberlin** [comment]
test

**Comment by pascalhpi** [comment]
hmm also bei lasse, alex und mir kam der fehler jedenfalls. ich hab keine ahnung was da abgeht

**Comment by pinussilvestrus** [comment]
@pascalhpi @kremer-io ist der fehler noch aktuell?
