### ISSUE TITLE
Add polyfill for colorpicker

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/schulcloud-client#564]
Like in course edit or course create. Cause Safari is not support HTM5 plain type="color"
http://bgrins.github.io/spectrum/

**Comment by adrianjost** [comment]
Nice easy UI: https://rakujira.jp/projects/iro/

**Comment by janrenz** [comment]
Aber wir wollen ja nur ein festes Set an Farben...

**Comment by adrianjost** [comment]
#580
