### ISSUE TITLE
"Cannot read property 'addEventListener' of null" on start page

### ISSUE THREAD

**Issue by schurigh** [schul-cloud/schulcloud-client#655]
2 errors on current start page, .mobile-nav-toggle seems to be the problem
![a](https://user-images.githubusercontent.com/6624503/39244583-54d8d7f0-4891-11e8-8cf6-bf7efc505df2.png)

**Comment by alekpentchev** [comment]
I could take a look at it.
Can you tell me only how to login to the app for development purposes? I have setup eveything else, app starts, but I am stuck at homepage. I was not able to find instructions in the documentation. And I am sorry for this off-topic.

**Comment by janrenz** [comment]
@schurigh isn't that fixed by @adrianjost

**Comment by schurigh** [comment]
Yes, fixed by now. 👍
