### ISSUE TITLE
main-content container sollte die verfügbare Höhe annehmen

### ISSUE THREAD

**Issue by Michael-Janke** [schul-cloud/schulcloud-client#809]
Für meine Masterarbeit (Digitaler Klassenraum) brauche ich eine Höhe, die mindestens so hoch ist wie die verfügbare Höhe: also (100% - footer). Habe es dynamisch mit flex gelöst.

Außerdem habe ich für den .content-wrapper das unnötige calc(100%-x) entfernt. (margin zählt nicht zu der Breite, padding schon)

Ich habe in meinem merge-request entsprechende Änderung schon gemacht.

**Comment by adrianjost** [comment]
Ist schon gemered und kann geschlossen werden oder?
