### ISSUE TITLE
Uploading two files with the same name does not replace/update the first file

### ISSUE THREAD

**Issue by Parnswir** [schul-cloud/schulcloud-client#838]
## Current Behavior

1. Upload a file "name.ext" (version 1)
2. Locally change the file
3. Upload changed file with the same name "file.ext" (version 2)
4. Upload succeeds, the page reloads
5. Only version 1 of the file is visible (but version 2 also exists in the file storage bucket)

## Expected Behavior
Either the file should be updated, or version 2 should be available as "file (1).ext" (or similar).

**Comment by Parnswir** [comment]
After a little digging, it seems that a 409 (conflict) error is thrown somewhere and printed to the console, but not caught/communicated to the frontend.

**Comment by janrenz** [comment]
Please move ticket to Ticketsystem.schul-cloud.org
